### ISSUE TITLE
Slide(s) with historical map + chart

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#65]
Could be 2 slides if necessary!

---

- [x] Map
- [x] Chart
- [x] Title
- [x] Text content
- [x] Design
- [x] Back-End providing data

---

Related issues: #23 #20 #22 #21 #5

**Comment by cecilediana** [comment]
Historical Map

**Comment by cecilediana** [comment]
Graph type: Line

**Comment by cecilediana** [comment]
Text: The total amount of cyclable paths is calculated in kilometers and includes the ones separated from  the main roads as well as the suggested paths and the Regional Cyclable Itineraries (RCI). The RCIs are suggested paths for cyclists willing to commute on a medium to long distance. These itineraries take into account the calmest streets and the less stressful paths for the users. The accuracy of the  really past data (1896-1970) are less reliable in terms of consistency. Nonetheless, the overall data remain as close as possible to the reality and can be trustworthy on a holistic vision of the infrastructure evolution. A significant year to mention is 2002, where the political courage and boldness allowed the apparition of a project considered as not realistic at its time. Hence, the suppression of one row of the street attributed to cars in order to construct a larger sideways shared by cyclists and pedestrians.

**Comment by Dakad** [comment]
Continued in #22
