### ISSUE TITLE
Font Circular Std Book

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#94]
This is a licensed font : <https://lineto.com/The+Fonts/Font+Categories/Text+Fonts/Circular/>

It's the "official" font used by Brussels Mobility and they gave us access to it so no issue there.

But 
- [ ] It should not be published on the GitHub repo ; we're using MIT license so we can't of course **not** change the font license
- [ ] It should be documented properly (not in an issue but in README or INSTALL file) !

**Comment by Dakad** [comment]
Solution  
----------
@danielleterras
Set an alternative font to use and remove the Circular Stb Font from the repo

**Comment by jbelien** [comment]
We can keep "Font Circular Std Book" on the website as this is the "official" Brussels Mobility font (**but not published in the repo**).

But they seem to use "LL Circular Medium Web" on https://bike.brussels !
I don't know where that font comes from but if it's an "open" one that's also an option !

**Comment by danielleterras** [comment]
https://www.npmjs.com/package/circular-std

**Comment by danielleterras** [comment]
Instead of changing our project to the Open License we can tell the people in the README.md that we don't use an Open License, but if they want to use this font for any use, they should use the following package: https://www.npmjs.com/package/circular-std 

The Circular Std font family on this website is distributed under the Open Font License

**Comment by jbelien** [comment]
Don't forget to remove the font files from the repo!
